#!/bin/bash

#direc="/Users/zx/workdir/so"
direc="/Users/lion/CloudStation/workdir/sss"
pw="$direc/passwd"
COM_USER="$1"
COMMAND="$2"


function color(){
    blue="\033[0;36m"
    red="\033[0;31m"
    green="\033[0;32m"
    close="\033[m"
    case $1 in
        blue)
            echo -e "$blue $2 $close"
        ;;
        red)
            echo -e "$red $2 $close"
        ;;
        green)
            echo -e "$green $2 $close"
        ;;
        *)
            echo "Input color error!!"
        ;;
    esac
}

function copyright(){
    echo "#########################"
    color blue "  SSH Login Platform   "
    echo "#########################"
    echo
}

function underline(){
    echo "-------------------------------------------------------------------------------------------"
}

function print_t(){


    echo "序号 |       主机      |       主机名     |           用户            |      说明      "
    underline
    awk  'BEGIN {FS=":"} {printf("\033[0;31m% 3s \033[m | %15s | %16s | %25s | %s\n",$1,$2,$3,$8,$9)}' $pw
    underline

 }

function USE_N(){
    read -p '[*] 选择主机: ' number
    ipaddr=$(awk -v num=$number 'BEGIN {FS=":"} {if($1 == num) {print $2}}' $pw)
    port=$(awk -v num=$number 'BEGIN {FS=":"} {if($1 == num) {print $4}}' $pw)
    username=$(awk -v num=$number 'BEGIN {FS=":"} {if($1 == num) {print $6}}' $pw)
    way=$(awk -v num=$number 'BEGIN {FS=":"} {if($1 == num) {print $5}}' $pw)
    passwd=$(awk -v num=$number 'BEGIN {FS=":"} {if($1 == num) {print $7}}' $pw)
    case $number in
        [0-9]|[0-9][0-9]|[0-9][0-9][0-9])
   	   if [[ "$way" == "pk" ]];then	
   	clear
		ssh -i $HOME/.ssh/$passwd $username@$ipaddr -p $port
		echo "ssh -i $direc/$passwd $username@$ipaddr -p $port"
	   elif [[ "$way" == "passwd" ]];then
#                expect -f $direc/ssh_login.exp $ipaddr $username $passwd $port
								clear
                echo "ssh $username@$ipaddr"
                sshpass -p $passwd ssh -p $port $username@$ipaddr 
           fi
        ;;
        "q"|"quit")
            exit
        ;;

        *)
            echo "Input error!!"
        ;;
    esac

}

function SSH_IP(){
    COM_USER="$1"
    IPADDR=$(awk -v Users="\\("$COM_USER"\\)" 'BEGIN {FS=":"} {if($8 ~ Users) {print $2}}' $pw)
}

function SSH_WITH_USER(){
   port=$(awk -v IP=$IPADDR 'BEGIN {FS=":"} {if($2 == IP) {print $4}}' $pw)
   passwd=$(awk -v IP=$IPADDR 'BEGIN {FS=":"} {if($2 == IP) {print $7}}' $pw)
   username=$(awk -v IP=$IPADDR 'BEGIN {FS=":"} {if($2 == IP) {print $6}}' $pw)
}



if [ $# -lt 1 ]; then
    copyright
    print_t
    USE_N
elif [ $# -eq 1 ]; then 
    echo 123
elif [ $# -eq 2 ]; then
    clear
    SSH_IP $COM_USER 
    SSH_WITH_USER
    echo "ssh -p $port $username@$IPADDR"
    sshpass -p $passwd ssh -p $port $username@$IPADDR "su - $COM_USER -c '$COMMAND'"
fi

